# Generated by Django 4.1.7 on 2023-03-13 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='company',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_company_pciture.jpg', upload_to='company_profile_images'),
        ),
        migrations.AddField(
            model_name='job',
            name='timeline',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='skills',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='skills',
            field=models.ManyToManyField(to='jobs.skill'),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.category'),
        ),
    ]
