# Generated by Django 4.1.7 on 2023-04-04 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.freelancer'),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
