# Generated by Django 4.1.7 on 2023-03-14 09:31

from django.db import migrations, models

def create_categories(apps, schema_editor):
    Category = apps.get_model('jobs', 'Category')
    categories = ['Backend', 'Frontend', 'UI', 'Website']
    for category in categories:
        Category.objects.create(name=category)


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='timeline',
            field=models.TextField(),
        ),
        migrations.RunPython(create_categories),
    ]
