# Generated by Django 4.1.7 on 2023-03-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_category_skill_remove_job_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_picture.png', upload_to='company_profile_images'),
        ),
    ]
