# Generated by Django 4.1.7 on 2023-04-10 06:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_freelancer_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30, null=True), blank=True, null=True, size=None),
        ),
    ]
