# Generated by Django 4.1.7 on 2023-03-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_company_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='default_picture.png', upload_to='company_profile_images'),
        ),
    ]
