# Generated by Django 4.1.7 on 2023-03-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='education_specialization',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='education_university',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='education_year_of_study',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='experience_company_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='experience_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='experience_position',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='experience_work_duration',
            field=models.CharField(default='', max_length=20),
        ),
    ]
