# Generated by Django 4.1.7 on 2023-03-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_company_profile_picture_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='photo',
            field=models.ImageField(blank=True, default='default_picture.png', upload_to='company_profile_images'),
        ),
    ]
