# Generated by Django 4.1.7 on 2023-03-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_freelancer_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='skills',
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='photo',
            field=models.ImageField(blank=True, default='default_picture.png', upload_to='freelancer_profile_images'),
        ),
    ]
