# Generated by Django 4.1.7 on 2023-04-26 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_company_description_alter_freelancer_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='education_specialization',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='education_university',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='education_year_of_study',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='experience_company_name',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='experience_description',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='experience_position',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='experience_work_duration',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='skills',
        ),
        migrations.AddField(
            model_name='skill',
            name='freelancer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='jobs.freelancer'),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('freelancer', 'name')},
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('platform', models.CharField(max_length=50)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('work_duration', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='jobs.freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=30)),
                ('specialization', models.CharField(max_length=30)),
                ('year_of_study', models.CharField(max_length=20)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='jobs.freelancer')),
            ],
        ),
    ]
