# Generated by Django 4.1.7 on 2023-03-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_freelancer_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='field',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
