# Generated by Django 4.1.7 on 2023-03-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_freelancer_skills_alter_freelancer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
