# Generated by Django 4.1.7 on 2023-03-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_freelancer_first_name_freelancer_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='occupation',
            field=models.CharField(default='', max_length=20),
        ),
    ]
