# Generated by Django 4.1.7 on 2023-04-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='facebook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website_link',
            field=models.URLField(blank=True),
        ),
    ]
