# Generated by Django 4.1.7 on 2023-04-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_position_job_position_alter_freelancer_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='occupation',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
