# Generated by Django 4.1.7 on 2023-05-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_job_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
