# Generated by Django 4.1.7 on 2023-05-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_submission_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='freelancer_files/'),
        ),
    ]
