# Generated by Django 4.2.1 on 2023-05-14 06:36

from django.db import migrations


def put_data(apps, schema_editor):
    Category = apps.get_model('jobs', 'Category')
    Category.objects.create(id=1001,name='Graphics & Design ')
    Category.objects.create(id=1002,name='Digital Marketing ')
    Category.objects.create(id=1003,name='Writing & Translation ')
    Category.objects.create(id=1004,name='Video & Animation ')
    Category.objects.create(id=1005,name='Music & Audio ')
    Category.objects.create(id=1006,name='Programming & Tech ')
    Category.objects.create(id=1007,name='Photography ')
    Category.objects.create(id=1008,name='Business')
    Skill=apps.get_model('jobs', 'Skill')
    Skill.objects.create(id=1001,name='Spring Framework')
    Skill.objects.create(id=1002,name='MySQL')
    Skill.objects.create(id=1003,name='Jira')
    Skill.objects.create(id=1004,name='PostgreSQL')
    Skill.objects.create(id=1005,name='XML')

class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_alter_submission_file'),
    ]

    operations = [
        migrations.RunPython(put_data),
    ]
